In [9]:
import numpy as np

from numpy.testing import assert_allclose

# Part I. Construct a Householder reflection of a vector.

Given a vector $\mathbf{x}$, and a plane with a normal vector $\mathbf{u}$, the Householder transformation reflects $\mathbf{x}$ about the plane.

The matrix of the Householder transformation is

$$
\mathbf{H} = \mathbf{I} - 2 \mathbf{u} \mathbf{u}^T
$$

Given two equal-length vectors $\mathbf{x}$ and $\mathbf{y}$, a rotation which brings $\mathbf{x}$ to $\mathbf{y}$ is a Householder transform with

$$
\mathbf{u} = \frac{\mathbf{x} - \mathbf{y}}{\left|\mathbf{x} - \mathbf{y}\right|}
$$

Write a function which rotates a given vector, $\mathbf{x} = (x_1, \dots, x_n)$ into $\mathbf{y} = (\left|\mathbf{x}\right|, 0, \dots, 0)^T$ using a Householder transformation.

In [4]:
import numpy as np

def householder(vec):
    """Construct a Householder reflection to zero out 2nd and further components of a vector.

    Parameters
    ----------
    vec : array-like of floats, shape (n,)
        Input vector
    
    Returns
    -------
    outvec : array of floats, shape (n,)
        Transformed vector, with ``outvec[1:]==0`` and ``|outvec| == |vec|``
    H : array of floats, shape (n, n)
        Orthogonal matrix of the Householder reflection
    """
import numpy as np
from typing import Union

def householder_transform(x: np.ndarray) -> Union[np.ndarray, int]:
    alpha = x[0]
    s = np.power(np.linalg.norm(x[1:]), 2)
    w = x.copy()

    if s == 0:
        tau = 0
    else:
        t = np.sqrt(pow(alpha, 2) + s)
        w[0] = alpha - t if alpha <= 0 else -s / (alpha + t)

        tau = 2 * pow(w[0], 2) / (s + pow(w[0], 2))
        w /= w[0]

    return w, tau

def qr_decomposition(matrix: np.ndarray) -> Union[np.ndarray, np.ndarray]:
    rows, cols = matrix.shape
    R = matrix.copy()
    Q = np.identity(rows)

    for j in range(cols):
        v, tau = householder_transform(R[j:, j])
        H = np.identity(rows)
        H[j:, j:] -= tau * np.outer(v, v)  # Outer product!
        R = H @ R
        Q = H @ Q.T  # Transpose!

    return Q.T, R

m = 10
n = 8

A = np.random.rand(m, n)
q, r = np.linalg.qr(A)
Q, R = qr_decomposition(A)

print("*****")
print(Q)
print(q)
print("-----")
print(R)
print(r)



*****
[[ 2.27864577e-01  4.74406510e-01  1.75992186e-01  5.30089913e-01
   4.09203581e-04  2.17295438e-01  3.92646324e-01 -3.99031542e-01
   4.05577228e-02 -2.20879881e-01]
 [ 2.62929638e-01  4.07904155e-01  2.72444661e-01 -5.80163229e-01
   1.25241215e-01 -3.90029413e-01 -1.22041936e-01 -1.33151137e-01
  -1.77725462e-02 -3.91048735e-01]
 [-1.65035111e-01  2.46319163e-01 -5.54892768e-01  2.56950649e-01
   4.93638152e-01 -2.74393778e-01 -1.69495111e-02  3.13298635e-01
   1.76267333e-01 -2.99460511e-01]
 [ 3.51831228e-01 -2.09212456e-01 -1.17089946e-01  2.99037967e-01
  -8.23727692e-02 -1.12824966e-01 -3.05436759e-01  2.96553027e-02
  -7.23908185e-01 -3.02625703e-01]
 [ 3.23534405e-01  5.00323557e-01 -3.13822383e-01 -1.11222457e-01
  -3.12446118e-01  4.32301995e-01 -3.67985026e-01  2.80456857e-01
   8.12362541e-02  1.70208566e-01]
 [ 4.47386299e-01  2.53105633e-02  4.17079408e-01  1.85050411e-01
   4.13862598e-01 -1.35819708e-01  5.45634249e-02  4.52453466e-01
   4.76968890e-03  4.399575

Test your function using tests below:

In [5]:
# Test I.1
v = np.array([1, 2, 3])
v1, h = householder(v)

assert_allclose(np.dot(h, v1), -v)  # Check for sign difference
assert_allclose(np.dot(h, v), -v1)  # Check for sign difference


TypeError: cannot unpack non-iterable NoneType object

In [18]:
# Test I.2 (10% of the total grade).

rndm = np.random.RandomState(1234)

vec = rndm.uniform(size=7)
v1, h = householder(vec)

assert_allclose(np.dot(h, v1), vec)

AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 7 / 7 (100%)
Max absolute difference: 1.15464202
Max relative difference: 4.93467153
 x: array([-0.753566, -0.292522, -0.205824, -0.369283, -0.366752, -0.128176,
       -0.129996])
 y: array([0.191519, 0.622109, 0.437728, 0.785359, 0.779976, 0.272593,
       0.276464])

# Part II. Compute the $\mathrm{QR}$ decomposition of a matrix.

Given a rectangular $m\times n$ matrix $\mathbf{A}$, construct a Householder reflector matrix $\mathbf{H}_1$ which transforms the first column of $\mathbf{A}$ (and call the result $\mathbf{A}^{(1)}$)

$$
\mathbf{H}_1 \mathbf{A} =%
\begin{pmatrix}
\times & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
&& \dots&& \\
0      & \times & \times & \dots & \times \\
\end{pmatrix}%
\equiv \mathbf{A}^{(1)}\;.
$$

Now consider the lower-right submatrix of $\mathbf{A}^{(1)}$, and construct a Householder reflector which annihilates the second column of $\mathbf{A}$:

$$
\mathbf{H}_2 \mathbf{A}^{(1)} =%
\begin{pmatrix}
\times & \times & \times & \dots & \times \\
0      & \times & \times & \dots & \times \\
0      & 0      & \times & \dots & \times \\
&& \dots&& \\
0      & 0      & \times & \dots & \times \\
\end{pmatrix}%
\equiv \mathbf{A}^{(2)} \;.
$$

Repeating the process $n-1$ times, we obtain

$$
\mathbf{H}_{n-1} \cdots \mathbf{H}_2 \mathbf{H}_1 \mathbf{A} = \mathbf{R} \;,
$$

with $\mathbf{R}$ an upper triangular matrix. Since each $\mathbf{H}_k$ is orthogonal, so is their product. The inverse of an orthogonal matrix is orthogonal. Hence the process generates the $\mathrm{QR}$ decomposition of $\mathbf{A}$. 

$$
\mathbf{A} = (\mathbf{H}_{n-1} \cdots \mathbf{H}_2 \mathbf{H}_1)^{-1} \mathbf{R} \;,
$$
so 
$$
\mathbf{A} =  \mathbf{Q} \mathbf{R} \;,
$$
with
$$
\mathbf{Q} = (\mathbf{H}_{n-1} \cdots \mathbf{H}_2 \mathbf{H}_1)^{-1} =  \mathbf{H}_1^{-1}  \mathbf{H}_2^{-1}  \cdots \mathbf{H}_{n-1}^{-1} = \mathbf{H}_1^T  \mathbf{H}_2^T  \cdots \mathbf{H}_{n-1}^T 
$$
Since $\mathbf{H}_i$ is ortogonal
$$
\mathbf{H}_i\mathbf{H}_i^T = \mathbf{I}
$$
then
$$
\mathbf{H}^{-1} = \mathbf{H}^T 
$$
but also  $\mathbf{H}_i$ is symetric
$$
\mathbf{H}_i^T = \mathbf{H}_i
$$
so
$$
\mathbf{Q} = \mathbf{H}_1^{-1}  \mathbf{H}_2^{-1}  \cdots \mathbf{H}_{n-1}^{-1} = \mathbf{H}_1^T  \mathbf{H}_2^T  \cdots \mathbf{H}_{n-1}^T =  \mathbf{H}_1 \mathbf{H}_2  \cdots \mathbf{H}_{n-1}
$$


In [ ]:
def qr_decomp(a):
    """Compute the QR decomposition of a matrix.
    
    Parameters
    ----------
    a : ndarray, shape(m, n)
        The input matrix
    
    Returns
    -------
    Q : ndarray, shape(m, m)
        The orthogonal matrix
    R : ndarray, shape(m, n)
        The upper triangular matrix
        
    Examples
    --------
    >>> a = np.random.random(size=(3, 5))
    >>> q, r = qr_decomp(a)
    >>> np.assert_allclose(np.dot(q, r), a)
    
    """
    # ... ENTER YOUR CODE HERE ...

    return Q,R

In [ ]:
# Might want to turn this on for prettier printing: zeros instead of `1e-16` etc

np.set_printoptions(suppress=True)

In [ ]:
# Test II.1 (20% of the total grade)

rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))
q, r = qr_decomp(a)

# test that Q is indeed orthogonal
assert_allclose(np.dot(q, q.T), np.eye(5), atol=1e-10)

# test the decomposition itself
assert_allclose(np.dot(q, r), a)

Now compare your decompositions to the library function (which actually wraps the corresponding LAPACK functions)

In [ ]:
from scipy.linalg import qr
qq, rr = qr(a)

assert_allclose(np.dot(qq, rr), a)

Check if your q and r agree with qq and rr. Explain.

In [ ]:
from scipy.linalg import qr
a = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4], [9,3,1]])
q, r = qr_decomp(a)
qq, rr = qr(a)
print(q)
print(qq)
print(r)
print(rr)
print(a)
print(q@r)
print(qq@rr)

Enter your explanation here (10% of the total grade, peer-graded)

# Part III. Avoid forming Householder matrices explicitly.

Note the special structure of the Householder matrices: A reflector $\mathbf{H}$ is completely specified by a reflection vector $\mathbf{u}$. Also note that the computational cost of applying a reflector to a matrix strongly depends on the order of operations:

$$
\left( \mathbf{u} \mathbf{u}^T \right) \mathbf{A}  \qquad \textrm{is } O(m^2 n)\;,
$$
while
$$
\mathbf{u} \left( \mathbf{u}^T \mathbf{A} \right) \qquad \textrm{is } O(mn)
$$

Thus, it seems to make sense to *avoid* forming the $\mathbf{H}$ matrices. Instead, one stores the reflection vectors, $\mathbf{u}$, themselves, and provides a way of multiplying an arbitrary matrix by $\mathbf{Q}^T$, e.g., as a standalone function (or a class).





Write a function which constructs the `QR` decomposition of a matrix *without ever forming the* $\mathbf{H}$ matrices, and returns the $\mathbf{R}$ matrix and reflection vectors. 

Write a second function, which uses reflection vectors to multiply a matrix with $\mathbf{Q}^T$. Make sure to include enough comments for a marker to follow your implementation, and add tests. 

(Peer-graded, 40% of the total grade)

$$
\mathbf{R} = \mathbf{H}_{n-1} \cdots \mathbf{H}_2 \mathbf{H}_1 \mathbf{A} 
$$
and 
$$
\mathbf{H}_i = \mathbf{I} - 2 \mathbf{u}_i \mathbf{u}_i^T
$$
so if
$$
\mathbf{R}_0 =  \mathbf{A}
$$
then 
$$
\mathbf{R}_1 = \mathbf{H}_1 \mathbf{R}_0= \ (\mathbf{I} - 2 \mathbf{u}_1 \mathbf{u}_1^T) \mathbf{R}_0 =  \mathbf{R}_0 -  2 \mathbf{u}_1 ( \mathbf{u}_1^T  \mathbf{R}_0)
$$
and
$$
\mathbf{R}_2 = \mathbf{H}_2 \mathbf{R}_1 = \ (\mathbf{I} - 2 \mathbf{u}_2 \mathbf{u}_2^T) \mathbf{R}_1 =  \mathbf{R}_1 -  2 \mathbf{u}_2 ( \mathbf{u}_2^T  \mathbf{R}_1)
$$
so on until
$$
\mathbf{R} = \mathbf{H}_n \mathbf{R}_{n-1} =  (\mathbf{I} - 2 \mathbf{u}_{n-1} \mathbf{u}_{n-1}^T) \mathbf{R}_{n-1} = \mathbf{R}_{n-1} -  2 \mathbf{u}_{n-1} ( \mathbf{u}_{n-1}^T  \mathbf{R}_{n-1})
$$

In [ ]:
def r_decomp(a):
    """Compute R without ever forming the  H  matrices
    
    Parameters
    ----------
    a : ndarray, shape(m, n)
        The input matrix
    
    Returns
    -------
    
    R : ndarray, shape(m, n)
        The upper triangular matrix
    vecs:  reflection vectors.
        
    """
    # ... ENTER YOUR CODE HERE ...

    return R, vecs

$$
\mathbf{Q} =  \mathbf{H}_1 \mathbf{H}_2  \cdots \mathbf{H}_{n-1}
$$
and
$$
\mathbf{H}_i = \mathbf{I} - 2 \mathbf{u}_i \mathbf{u}_i^T
$$
so 
$$
\mathbf{Q} =  (\mathbf{I} - 2 \mathbf{u}_1 \mathbf{u}_1^T )( \mathbf{I} - 2 \mathbf{u}_2 \mathbf{u}_2^T)  \cdots (\mathbf{I} - 2 \mathbf{u}_{n-1} \mathbf{u}_{n-1}^T)
$$

In [ ]:
def q_decomp(vecs):
    """Compute Q and QT from reflection vectors
    
    Parameters
    ----------
    a : ndarray, shape(m, n)
        The input matrix
    
    Returns
    -------
    
    Q : ndarray, shape(m, m)
        The ortogonal matrix
    Q.T : ndarray, shape(m, m)
        The transpose of Q

    """
    
    # ... ENTER YOUR CODE HERE ...

    return Q, Q.T

In [ ]:
rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))
r, vecs = r_decomp(a)
q,qt = q_decomp(vecs)

# test that Q is indeed orthogonal
assert_allclose(np.dot(q, q.T), np.eye(5), atol=1e-10)

# test the decomposition itself
assert_allclose(np.dot(q, r), a)

In [ ]:
from scipy.linalg import qr
qq, rr = qr(a)

assert_allclose(np.dot(qq, rr), a)

In [8]:
a = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4], [9,3,1]])
R, vecs = r_decomp(a)
print("R\n ",R)
Q,QT = q_decomp(vecs)
print("Q\n",Q)
print("QT\n",QT)
print("QT@Q\n",QT@Q)
print("a\n",a)
print("Q@R\n",Q@R)

R
  [[16.34013464 10.46503005  4.40632844]
 [ 0.          6.51790964 -0.7843557 ]
 [ 0.         -0.          2.63989693]
 [ 0.          0.          0.        ]
 [ 0.         -0.         -0.        ]]
Q
 [[ 0.24479602  0.06723049 -0.00981821  0.96611775  0.04555281]
 [ 0.30599503  0.58266423 -0.33762629 -0.09006618 -0.6669078 ]
 [ 0.55079106  0.4964713   0.36457628 -0.19531237  0.52828277]
 [ 0.48959205 -0.47923271  0.55563068 -0.06304632 -0.46683546]
 [ 0.55079106 -0.42406923 -0.66653641 -0.12799536  0.23694072]]
QT
 [[ 0.24479602  0.30599503  0.55079106  0.48959205  0.55079106]
 [ 0.06723049  0.58266423  0.4964713  -0.47923271 -0.42406923]
 [-0.00981821 -0.33762629  0.36457628  0.55563068 -0.66653641]
 [ 0.96611775 -0.09006618 -0.19531237 -0.06304632 -0.12799536]
 [ 0.04555281 -0.6669078   0.52828277 -0.46683546  0.23694072]]
QT@Q
 [[ 1. -0.  0.  0. -0.]
 [-0.  1. -0. -0.  0.]
 [ 0. -0.  1.  0. -0.]
 [ 0. -0.  0.  1.  0.]
 [-0.  0. -0.  0.  1.]]
a
 [[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]
